In [ ]:
###1. Load Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
###2. Import dataset

flower_df = pd.read_csv("../data/raw/iris.csv")
flower_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Note: The raw dataset given in the url was retireved from its original github repo and downloaded.

In [ ]:
###3. Inspect the dataset
flower_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [8]:
flower_df.shape

(150, 5)

In [13]:
flower_df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [9]:
flower_df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:
flower_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
flower_df.duplicated().sum()

np.int64(1)

In [14]:
flower_df.drop_duplicates(inplace=True)

In [15]:
flower_df.duplicated().sum()

np.int64(0)

In [16]:
flower_df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     49
Name: count, dtype: int64

INTERPRETATION 

The iris dataset is one that is favorable for analysis and modeling as a beginner. The size of this dataset is quite small, occupying just 150 rows and 5 columns. This means that we have 150 counts of each variable. The variables include sepal_length, sepal_width, petal_length, petal_width, and the soon-to-be target variable, species.

The first 4 variables that indicate the size of the flower parts are continuous while the species variable is categorical, with 3 classes each having a count of 50 observations. The description table gives us a summary of the descriptive statistics of the dataset.

The dataset is mostly quite clean. It had no missing values, but it did have 1 duplicated row. Because it's only one, I discarded it to ensure the dataset is clean. Having the rechecked, the dataset is now clean. This means now that right now, one of the variables is short by one observation, which is 'virginica'. Regardless, the target is still balanced across the 3 species.

In [19]:
#Save the cleaned dataset to a new CSV file

from pathlib import Path

# Create the processed-data directory if it does not exist
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

# Save the cleaned dataset
flower_df.to_csv(processed_dir / "iris_cleaned.csv", index=False)